<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <PublishReadyToRun>false</PublishReadyToRun>
    <TieredCompilation>false</TieredCompilation>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../ContentBuilderExample.Core/Assets/Icon.ico</ApplicationIcon>
    <AssemblyName>ContentBuilderExample</AssemblyName>
    <MonoGamePlatform>DesktopVK</MonoGamePlatform>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ContentBuilderExample.Core\ContentBuilderExample.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
      <UpToDateCheckInput Include="..\Content\Assets\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.Native" Version="3.8.5" />
    <PackageReference Include="MonoGame.Runtime.Windows.Vulkan" Version="3.8.5" />
    <PackageReference Include="MonoGame.Runtime.Linux.Vulkan" Version="3.8.5" />
    <PackageReference Include="MonoGame.Runtime.Mac.Vulkan" Version="3.8.5" />
  </ItemGroup>
  <Import Project="..\ContentBuilderExample.Content\BuildContent.targets" />
</Project>