<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0-ios</TargetFramework>
    <SupportedOSPlatformVersion>12.2</SupportedOSPlatformVersion>
    <CodesignKey>iPhone Developer</CodesignKey>
    <MonoGamePlatform>iOS</MonoGamePlatform>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\ContentBuilderExample.Core\ContentBuilderExample.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
      <UpToDateCheckInput Include="..\Content\Assets\**\*" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.iOS" Version="3.8.5" />
  </ItemGroup>
  <Import Project="..\ContentBuilderExample.Content\BuildContent.targets" />
</Project>