<Project>
  <Target Name="BuildContent" BeforeTargets="BeforeCompile">
    <PropertyGroup>
      <ContentOutput>$([MSBuild]::NormalizeDirectory('$(ProjectDir)', '$(OutputPath)'))</ContentOutput>
      <ContentTemp>$([MSBuild]::NormalizeDirectory('$(ProjectDir)', '$(IntermediateOutputPath)'))</ContentTemp>
      <ContentArgs>build -p $(MonoGamePlatform) -s ContentBuilderExample.Content/Assets -o &quot;$(ContentOutput.TrimEnd('\/'))&quot; -i &quot;$(ContentTemp.TrimEnd('\/'))&quot;</ContentArgs>
    </PropertyGroup>
    <MSBuild Projects="$(MSBuildThisFileDirectory)ContentBuilderExample.Content.csproj" Targets="Build" RemoveProperties="TargetFramework;RuntimeIdentifier;RuntimeIdentifiers;SelfContained;PublishReadyToRun;PublishSingleFile;PublishTrimmed;PublishAot">
      <Output TaskParameter="TargetOutputs" ItemName="ContentBuilderAssembly" />
    </MSBuild>
    <PropertyGroup>
      <ContentCommand>@(ContentBuilderAssembly->'%(RootDir)%(Directory)%(Filename)')</ContentCommand>
    </PropertyGroup>
    <Exec Command="$(ContentCommand) $(ContentArgs)" WorkingDirectory="$(MSBuildThisFileDirectory)..\" CustomErrorRegularExpression="\[E\] .+" CustomWarningRegularExpression="\[W\] .+" />
  </Target>
  <Target Name="AddGeneratedContentAssets"
    AfterTargets="BuildContent">
    <ItemGroup>
      <GeneratedAsset Include="$(ContentOutput)Content\**\*" />

      <ResolvedFileToPublish Include="@(GeneratedAsset)"
        Condition="'$(MonoGamePlatform)' != 'Android' And '$(MonoGamePlatform)' != 'MacOSX' And '$(MonoGamePlatform)' != 'iOS'">
        <RelativePath>Content/%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</RelativePath>
        <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      </ResolvedFileToPublish>

      <AndroidAsset Include="@(GeneratedAsset)"
        Condition="'$(MonoGamePlatform)' == 'Android'">
        <Link>Content\%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</Link>
      </AndroidAsset>

      <BundledResource Include="@(GeneratedAsset)"
        Condition="'$(MonoGamePlatform)' == 'MacOSX' Or '$(MonoGamePlatform)' == 'iOS'">
        <Link>Content\%(GeneratedAsset.RecursiveDir)%(GeneratedAsset.Filename)%(GeneratedAsset.Extension)</Link>
      </BundledResource>
    </ItemGroup>
  </Target>
</Project>
